In [1]:
import simulator_base_constants
from simulator_base_constants import *
import simulator_base_classes
from simulator_base_classes import *
from scene_preparer import drawSceneWalls

width = DEFAULT_WIDTH * 2
height = DEFAULT_HEIGHT
O = np.array([DEFAULT_WIDTH, DEFAULT_HEIGHT * 0.5, 0])
pygame.init()
sc = pygame.display.set_mode((width , height))
running = True
objectsDescriptor = [np.array([[-1364, -662, 0], [-666, -664, 0], [-668, -116, 0], [-500, -118, 0], [-504, -662, 0], [172, -668, 0], [192, 184, 0], [-1028, 218, 0], [-1030, 340, 0], [396, 332, 0], [390, -664, 0], [1338, -664, 0], [1342, -82, 0], [758, -78, 0], [758, 116, 0], [1338, 112, 0], [1346, 666, 0], [-122, 666, 0], [-136, 504, 0], [-548, 506, 0], [-546, 674, 0], [-1360, 660, 0]]),
 np.array([[-270, -438, 0], [-278, -2, 0], [-106, -2, 0], [0, -426, 0]])]
currentObject = []
while running:
    sc.fill(BGCOLOR)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        elif event.type == pygame.MOUSEBUTTONUP:
            pos = np.array(pygame.mouse.get_pos() + tuple([0]))
            pos = (pos - O) / scale
            print(pos)
            currentObject.append(pos)
        elif event.type == pygame.KEYUP:
            if event.key == 27:
                running = False
            elif event.key == 13:
                print("Fix object")
                if len(currentObject) > 0:
                    objectsDescriptor.append(currentObject)
                    currentObject = []
            elif event.key == 8:
                print("Cancel")
                if len(currentObject) > 0:
                    currentObject.pop()
                elif len(objectsDescriptor) > 0:
                    currentObject = list(objectsDescriptor[-1])
                    objectsDescriptor.pop()
            elif event.key == 32:
                print("Descriptor: ")
                res = '['
                for angles in objectsDescriptor:
                    if res[-1] == ')':
                        res += ',\n '
                    res += 'np.array(['
                    for a in angles:
                        if res[-1] == ']':
                            res += ', '
                        res += '['+str(int(a[0])) + ', ' + str(int(a[1])) + ', ' + str(int(a[2])) + ']'
                    res += '])'
                res += ']'
                print(res)
            else:
                print(event.key)
    drawSceneWalls(sc, O, objectsDescriptor)
    drawSceneWalls(sc, O, [currentObject], BLUE)
    if len(currentObject) > 0:
        pygame.draw.circle(sc, GREEN, tuple((currentObject[-1] * scale + O)[:2]), 10)

    pygame.display.update()
pygame.quit()

pygame 2.5.1 (SDL 2.28.2, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
Cancel
[1360. -654.    0.]
[842. -36.   0.]
[1378.  616.    0.]
[226. 606.   0.]
[254.  86.   0.]
[-458.  466.    0.]
[-642.  -40.    0.]
[-1062.   596.     0.]
[-1296.    30.     0.]
[-804. -328.    0.]
[-1328.  -358.     0.]
Fix object
[-504. -506.    0.]
[-236.   30.    0.]
[ 574. -204.    0.]
[ 780. -524.    0.]
Fix object
[496. 206.   0.]
[484. 470.   0.]
[972. 470.   0.]
[780. 220.   0.]


In [58]:
res = '['
for angles in objectsDescriptor:
    if res[-1] == ')':
        res += ',\n '
    res += 'np.array(['
    for a in angles:
        if res[-1] == ']':
            res += ', '
        res += '['+str(int(a[0])) + ', ' + str(int(a[1])) + ', ' + str(int(a[2])) + ']'
    res += '])'
res += ']'
print(res)

[np.array([[-672, -672, 0], [-116, -684, 0], [-114, -216, 0], [-64, -216, 0], [-68, -680, 0], [658, -690, 0], [654, -292, 0], [134, -286, 0], [134, -228, 0], [950, -242, 0], [940, -306, 0], [714, -302, 0], [706, -688, 0], [2070, -690, 0], [2070, 672, 0], [1560, 644, 0], [1522, -330, 0], [1446, -324, 0], [1466, 638, 0], [224, 642, 0], [198, 24, 0], [140, 28, 0], [126, 628, 0], [-656, 648, 0], [-664, 126, 0], [-48, 112, 0], [-54, 54, 0], [-674, 52, 0]]),
 np.array([[498, 26, 0], [558, -78, 0], [1300, 374, 0], [1210, 460, 0], [894, 274, 0], [730, 434, 0], [610, 356, 0], [764, 204, 0]]),
 np.array([[1130, 20, 0], [1208, 16, 0], [1234, -456, 0], [1784, -522, 0], [1790, 328, 0], [1844, 326, 0], [1850, -578, 0], [908, -552, 0], [904, -472, 0], [1150, -466, 0]])]


In [11]:
tuple([3])

(3,)