In [4]:
import simulator_executor
from simulator_executor import runSimulator
from coverage_problem_algorithms import \
    SWARMAlgorithm as SWARM, \
    VFASFAlgorithm as VFASF, \
    CSAAlgorithm as CSA, \
    SAAlgorithm as SA, \
    DSSAAlgorithm as DSSA, \
    SODAAlgorithm as SODA, \
    SSNDAlgorithm as SSND
import scene_preparer
from scene_preparer import *

def metricsPrint(rCnt, elapsedTime, energy, meanDistance, covaragePercentage, uniformity, sensorCoverageUniformity):
    print(str(rCnt) + "\t" + str(elapsedTime) + "\t" + str(energy) + "\t" + str(meanDistance) + "\t" + str(covaragePercentage) + "\t" + str(uniformity) + "\t" + str(sensorCoverageUniformity))

widths = [604, 704, 504, 504]
heights = [404, 504, 504, 504]
As = [1200 * 800 - 0.5 * (800-150) * 1200, 1400 * 1000 - 600 * 600, 1000 * 1000 - 300 * 300, 1000 * 1000 - 100 * 100]
scenes = [ButterflySceneGenerator(), ZigZagSceneGenerator(), OSceneGenerator(), TwoBoxesSceneGenerator()]

In [8]:
runSimulator(scenes[0], SODA, metricsPrint, A = As[0])

50	1.2	166.8991803830562	1.1020224830703684	52.32734392269555	0.49225807388760423	10.58289235442301


In [6]:
issubclass(SSND, DSSA)

True

In [11]:
getPointToSegmentProjection(np.array([0, 0]), np.array([0.5, 0]), np.array([0, 1]))

array([0.4, 0.2])

In [6]:
arr = np.array([5, 4, 3, 5, 7])
arr[np.array([1, 2, 3, 0, 2]) > 0]

array([5, 4, 3, 7])

In [8]:
np.array([1, 2, 3]).transpose()

array([1, 2, 3])

In [11]:
np.ones([4, 5]).T / np.array([1, 2, 3, 4])

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ]])

In [7]:
np.roll([[1, 2], [3, 4], [5, 6]], 2)

array([[5, 6],
       [1, 2],
       [3, 4]])

In [ ]:
#Multiple running
for i, sceneGenerator in enumerate(scenes):
    A = As[i]
    algorithms = [CSA(), SA(), SODA(A), DSSA(A), SSND(A), VFASF(), SWARM()]
    for algorithm in algorithms:
        runSimulator(sceneGenerator, algorithm, metricsPrint, widths[i], heights[i], np.array([widths[i] * 0.5, heights[i] * 0.5, 0]))

In [2]:
A = 1000 * 1000 - 100 * 100 * 2
algorithms = [CSA(), SA(), SODA(A), DSSA(A), SSND(A), VFASF(), SWARM()]    

for algorithm in algorithms:
    runSimulator(TwoBoxesSceneGenerator(), algorithm, metricsPrint)

35	3.92	119.17467927804609	2.556042308902794	93.11881005853981	0.10394360474669387	2.1479790090984223
35	3.16	107.65621931585142	2.545764175052714	91.06715511210928	0.2071766331556812	2.3033596631745286
35	48.0	4679.908460291121	2.1129632474818782	80.98284304701593	0.4178815640101852	3.2443866766837672
35	48.0	6533.0215528711005	2.1680741238281382	81.15312396450793	0.4206415865149754	3.11062712230728
35	48.0	1185.8797523962905	2.0679481697827367	80.76746069732337	0.40392447352900807	3.2555133918132935
35	7.54	84.29674119330431	2.0141888813499236	81.33721144287766	0.30233906088264684	3.354970744124546
35	48.0	6713.616577632802	2.0285947952760726	74.92636500865211	0.39984984609230473	4.976616332153699


In [1]:
runSimulator(ZigZagSceneGenerator(), SA(), metricsPrint)

NameError: name 'runSimulator' is not defined

In [3]:
runSimulator(OSceneGenerator(), SWARM(), metricsPrint)

In [ ]:
import simulator_executor
from simulator_executor import runSimulator
from SWARM_algorithm import SWARMAlgorithm as SWARM
from VFASF_algorithm import VFASFAlgorithm as VFASF
import scene_preparer
from scene_preparer import *
import threading

class simulatorThread(threading.Thread):
    def __init__(self, sceneGenerator, spawnCenter, algorithm, algName, pathToResults):
        threading.Thread.__init__(self)
        self.sceneGenerator = sceneGenerator
        self.spawnCenter = spawnCenter
        self.algorithm = algorithm
        self.file = open(pathToResults, "a")
        self.algName = algName

    def metricsFileWriter(self, rCnt, elapsedTime, energy, meanDistance, covaragePercentage, uniformity, sensorCoverageUniformity):
        print(self.algName+"\t"+str(rCnt) + "\t" + str(elapsedTime) + "\t" + str(energy) + "\t" + str(meanDistance) + "\t" + str(covaragePercentage) + "\t" + str(uniformity) + "\t" + str(sensorCoverageUniformity))
        self.file.write(str(rCnt) + "\t" + str(elapsedTime) + "\t" + str(energy) + "\t" + str(meanDistance) + "\t" + str(covaragePercentage) + "\t" + str(uniformity) + "\t" + str(sensorCoverageUniformity) + "\n")
    
    def run(self):
        print('Start ' + self.algName)
        runSimulator(self.sceneGenerator, self.spawnCenter, self.algorithm, self.metricsFileWriter)
        self.file.close()
        print('End ' + self.algName)

tVFASFOScene = simulatorThread(generateOscene, np.array([-300, 0, 0]), VFASF(), 'VFASFOScene', 'VFASFOSceneResults.txt')
tVFASFZigZagScene = simulatorThread(generateZigZagScene, np.array([-500, 0, 0]), VFASF(), 'VFASFZigZagScene', 'VFASFZigZagSceneResults.txt')
tVFASFButterflyScene = simulatorThread(generateButterflyScene, np.array([-300, 0, 0]), VFASF(), 'VFASFButterflyScene', 'VFASFButterflySceneResults.txt')
tSWARMOScene = simulatorThread(generateOscene, np.array([-300, 0, 0]), SWARM(), 'SWARMOScene', 'SWARMOSceneResults.txt')
tSWARMZigZagScene = simulatorThread(generateZigZagScene, np.array([-500, 0, 0]), SWARM(), 'SWARMZigZagScene', 'SWARMZigZagSceneResults.txt')
tSWARMButterflyScene = simulatorThread(generateButterflyScene, np.array([-300, 0, 0]), SWARM(), 'SWARMButterflyScene', 'SWARMButterflySceneResults.txt')

tVFASFOScene.start()
tVFASFZigZagScene.start()
tVFASFButterflyScene.start()
tSWARMOScene.start()
tSWARMZigZagScene.start()
tSWARMButterflyScene.start()
