In [1]:
import simulator_executor
from simulator_executor import runSimulator
from coverage_problem_algorithms import SWARM, VFASF, CSA, SA, DSSA, SODA, SSND, ESF
import scene_preparer
from scene_preparer import *

def metricsPrint(rCnt, elapsedTime, energy, meanDistance, covaragePercentage, uniformity, sensorCoverageUniformity):
    print(str(rCnt) + "\t" + str(elapsedTime) + "\t" + str(energy) + "\t" + str(meanDistance) + "\t" + str(covaragePercentage) + "\t" + str(uniformity) + "\t" + str(sensorCoverageUniformity))

widths = [604, 704, 504, 504]
heights = [404, 504, 504, 504]
As = [1200 * 800 - 0.5 * (800-150) * 1200, 1400 * 1000 - 600 * 600, 1000 * 1000 - 300 * 300, 1000 * 1000 - 100 * 100]
scenes = [ButterflySceneGenerator(), ZigZagSceneGenerator(), OSceneGenerator(), TwoBoxesSceneGenerator()]

pygame 2.5.1 (SDL 2.28.2, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html


In [ ]:
# for rCnt in [100, 150, 200]:
#     for sectorCount in [4, 6, 8, 10, 12, 16, 18]:
#         for speedCoef in [4, 8, 12]:
#             print([rCnt, speedCoef, sectorCount])
runSimulator(Maze3SceneGenerator(), 100, ESF(baseAlgorithm = SA()), metricsPrint, width = DEFAULT_WIDTH * 2, O = [DEFAULT_WIDTH, DEFAULT_HEIGHT * 0.5, 0])

In [4]:
from numpy import array
vo1 = {'Positions': [array([ 69.06924648, 127.51245505,   0.        ]), array([ 80.79313937, 121.16201307,   0.        ]), array([ 57.3453536 , 133.86289703,   0.        ]), array([ 92.51703226, 114.81157109,   0.        ]), array([ 45.62146071, 140.21333901,   0.        ]), array([104.24092515, 108.46112911,   0.        ]), array([ 33.89756782, 146.56378099,   0.        ]), array([115.96481803, 102.11068713,   0.        ]), array([ 22.17367494, 152.91422297,   0.        ]), array([127.68871092,  95.76024514,   0.        ]), array([ 10.44978205, 159.26466495,   0.        ]), array([139.41260381,  89.40980316,   0.        ]), array([ -1.27411084, 165.61510693,   0.        ]), array([  79.45186269, -146.68036189,    0.        ]), array([  67.7279698 , -153.03080387,    0.        ]), array([  91.17575558, -140.32991991,    0.        ]), array([  56.00407691, -159.38124585,    0.        ]), array([ 102.89964846, -133.97947793,    0.        ]), array([  44.28018403, -165.73168783,    0.        ]), array([ 114.62354135, -127.62903594,    0.        ]), array([151.13649669,  83.05936118,   0.        ]), array([-12.99800373, 171.96554891,   0.        ]), array([  32.55629114, -172.08212981,    0.        ]), array([ 126.34743424, -121.27859396,    0.        ]), array([  20.83239825, -178.43257179,    0.        ]), array([ 138.07132712, -114.92815198,    0.        ]), array([162.86038958,  76.7089192 ,   0.        ]), array([-24.72189661, 178.31599089,   0.        ]), array([-137.43075718, -122.19922488,    0.        ]), array([ 149.79522001, -108.57771   ,    0.        ]), array([   9.10850537, -184.78301377,    0.        ]), array([-36.4457895 , 184.66643287,   0.        ]), array([174.58428247,  70.35847722,   0.        ]), array([ 161.5191129 , -102.22726802,    0.        ]), array([  -2.61538752, -191.13345575,    0.        ]), array([-48.16968239, 191.01687485,   0.        ]), array([186.30817536,  64.00803524,   0.        ]), array([173.24300579, -95.87682604,   0.        ]), array([ -14.33928041, -197.48389773,    0.        ]), array([188.90007791,  62.60408803,   0.        ]), array([188.90007791,  62.60408803,   0.        ]), array([184.96689867, -89.52638406,   0.        ]), array([ -26.0631733 , -203.83433971,    0.        ]), array([-59.89357527, 197.36731683,   0.        ]), array([188.90007791, -87.39591197,   0.        ]), array([188.90007791, -87.39591197,   0.        ]), array([200.6239708 ,  68.95453001,   0.        ]), array([ -37.78706618, -210.18478169,    0.        ]), array([-71.61746816, 203.71775881,   0.        ]), array([-212.93753619,   53.9715418 ,    0.        ])], 'Labels': ['Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Agent', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Agent']}
vo2 = {'Positions': [array([ 68.25077898, 126.00143811,   0.        ]), array([ 79.97467187, 119.65099613,   0.        ]), array([ 56.52688609, 132.35188009,   0.        ]), array([ 91.69856475, 113.30055415,   0.        ]), array([ 44.8029932 , 138.70232207,   0.        ]), array([103.42245764, 106.95011217,   0.        ]), array([ 33.07910032, 145.05276405,   0.        ]), array([115.14635053, 100.59967019,   0.        ]), array([ 21.35520743, 151.40320604,   0.        ]), array([  9.63131454, 157.75364802,   0.        ]), array([126.87024341,  94.24922821,   0.        ]), array([138.5941363 ,  87.89878623,   0.        ]), array([ -2.09257835, 164.10409   ,   0.        ]), array([  78.45805217, -144.84563477,    0.        ]), array([  66.73415928, -151.19607675,    0.        ]), array([  90.18194505, -138.49519279,    0.        ]), array([  55.01026639, -157.54651873,    0.        ]), array([ 101.90583794, -132.14475081,    0.        ]), array([  43.28637351, -163.89696071,    0.        ]), array([ 113.62973083, -125.79430883,    0.        ]), array([150.31802919,  81.54834425,   0.        ]), array([-13.81647123, 170.45453198,   0.        ]), array([  31.56248062, -170.24740269,    0.        ]), array([ 125.35362372, -119.44386685,    0.        ]), array([  19.83858773, -176.59784467,    0.        ]), array([ 137.0775166 , -113.09342487,    0.        ]), array([162.04192208,  75.19790227,   0.        ]), array([-25.54036412, 176.80497396,   0.        ]), array([   8.11469484, -182.94828665,    0.        ]), array([ 148.80140949, -106.74298289,    0.        ]), array([-37.26425701, 183.15541594,   0.        ]), array([173.76581496,  68.84746029,   0.        ]), array([  -3.60919804, -189.29872863,    0.        ]), array([ 160.52530238, -100.39254091,    0.        ]), array([-144.7018835, -124.2841868,    0.       ]), array([184.90555977,  62.81343185,   0.        ]), array([184.90555977,  62.81343185,   0.        ]), array([-48.98814989, 189.50585792,   0.        ]), array([ -15.33309093, -195.64917061,    0.        ]), array([172.24919526, -94.04209892,   0.        ]), array([ -27.05698382, -201.99961259,    0.        ]), array([183.97308815, -87.69165694,   0.        ]), array([184.90555977, -87.18656815,   0.        ]), array([184.90555977, -87.18656815,   0.        ]), array([-60.71204278, 195.8562999 ,   0.        ]), array([196.62945266,  69.16387383,   0.        ]), array([ -38.78087671, -208.35005457,    0.        ]), array([-72.43593567, 202.20674188,   0.        ]), array([196.62945266, -93.53701013,   0.        ]), array([ -50.50476959, -214.70049656,    0.        ])], 'Labels': ['Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Agent', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall', 'Wall']}

In [8]:
len(vo2['Positions'])

50

In [6]:
A = ESF()
sec = A.getObjectSector(np.array([-200, 0]), 'Agent')

In [22]:
A.getAngleDistFromDirToSectors(np.array([cos(50/180 * mh.pi), sin(50/180 * mh.pi)]), [sec])/mh.pi * 180.0

70.00000000000001

In [26]:
sec1 = A.getObjectSector(np.array([1, 0]), 'Agent')
sec2 = A.getObjectSector(np.array([0, 1]), 'Agent')
vb = {'Positions': np.array([[0, -150], [-50, 100], [50, 100]]), 'Labels': ['Agent', 'Wall', 'Wall']}

In [62]:
w = 100
step = 10
m = 0
mx = 100
A.calcSpeed(
    {'Positions': np.array([[0, -150]] + [[-w, k] for k in range(m, mx, step)] + [[w, k] for k in range(m, mx, step)]),
     'Labels': ['Agent'] + ['Wall' for k in range(m, mx, step)] + ['Wall' for k in range(m, mx, step)]})

array([2.4492936e-16, 4.0000000e+00, 0.0000000e+00])

In [23]:
print(A.getObjectSector(np.array([1, 0]), 'Agent'))
print(A.getObjectSector(np.array([0, -200]), 'Agent'))

[array([ 0.5      , -0.8660254]), array([0.5      , 0.8660254])]
[array([-173.20508076, -100.        ]), array([ 173.20508076, -100.        ])]


In [5]:
dst = A.getAngleDistFromDirToSector(np.array([1, 0]), sec1)
print(dst / mh.pi * 180.0)
dst = A.getAngleDistFromDirToSector(np.array([1, 0]), sec2)
print(dst / mh.pi * 180.0)

dst = A.getAngleDistFromDirToSector(np.array([0, 1]), sec1)
print(dst / mh.pi * 180.0)
dst = A.getAngleDistFromDirToSector(np.array([0, 1]), sec2)
print(dst / mh.pi * 180.0)
print(A.getAngleDistFromDirToSectors(np.array([-1, 1]), [sec1, sec2]) / mh.pi * 180.0)

dst = A.getAngleDistFromDirToSector(np.array([0, -1]), sec1)
print(dst / mh.pi * 180.0)
dst = A.getAngleDistFromDirToSector(np.array([0, -1]), sec2)
print(dst / mh.pi * 180.0)

dst = A.getAngleDistFromDirToSector(np.array([-1, 0]), sec1)
print(dst / mh.pi * 180.0)
dst = A.getAngleDistFromDirToSector(np.array([-1, 0]), sec2)
print(dst / mh.pi * 180.0)

0.0
30.000000000000007
30.000000000000007
0.0
0.0
30.000000000000007
120.00000000000001
120.00000000000001
30.000000000000007


In [10]:
la/mh.pi*180.0

-60.0

In [11]:
ra/mh.pi*180.0

60.0

In [9]:
np.matmul(np.array([[1, 2], [3, 4]]), np.array([5, 6]))

array([17, 39])

In [3]:
runSimulator(Maze3SceneGenerator(), SA(speedCoef = 12, sectorCount = 6), metricsPrint, width = DEFAULT_WIDTH * 2, O = [DEFAULT_WIDTH, DEFAULT_HEIGHT * 0.5, 0], anchor_generation_count = 5)

TypeError: runSimulator() missing 1 required positional argument: 'metricsWriter'

In [2]:
from numpy import array
N = [[38.32438558696876, array([-34.00276514,  17.67966327,   0.        ])], [84.42833258601745, array([63.08966406, 56.10559359,  0.        ])], [109.02446404244479, array([105.24010467,  28.4755005 ,   0.        ])], [119.7426820138345, array([110.68717336,  45.67996879,   0.        ])], [77.21935548475878, array([-18.95252733,  74.85740157,   0.        ])], [55.56156357771031, array([ 5.20990829, 55.3167624 ,  0.        ])], [63.47671747662296, array([-59.11154248,  23.13264377,   0.        ])], [75.3076533197036, array([ 66.80259196, -34.76573538,   0.        ])], [84.58451456730053, array([67.42611717, 51.0711154 ,  0.        ])], [104.52562545146137, array([34.80428208, 98.56098784,  0.        ])], [26.523364088999582, array([-24.47867278,  10.21192546,   0.        ])], [2.232185784639499, array([-0.80396527,  2.08237682,  0.        ])], [35.78496555251286, array([-27.79970875,  22.53308574,   0.        ])], [17.925815527195017, array([ 9.65582544, 15.10297644,  0.        ])], [35.387904059745125, array([-34.83788875,  -6.21492248,   0.        ])], [89.89722554350948, array([81.61408628, 37.69153859,  0.        ])], [48.02670552674753, array([  3.60640639, -47.89110853,   0.        ])], [75.27595525487013, array([ 1.41550743, 75.2626453 ,  0.        ])], [81.11031664481199, array([80.59993009, -9.08486302,  0.        ])], [88.85720686864252, array([77.12900714, 44.12164401,  0.        ])], [94.03924582167885, array([87.95812952, 33.26781037,  0.        ])], [60.85962895068694, array([-32.13457705,  51.68426641,   0.        ])], [77.77913072146637, array([ 7.89678489, 77.37721864,  0.        ])], [19.548435604917902, array([-12.29999289, -15.19379839,   0.        ])], [149.40677244571035, array([ 99.28572452, 111.64554877,   0.        ])], [56.80991044275909, array([-31.81371148,  47.06648156,   0.        ])], [109.55853832431166, array([ 36.57388883, 103.27353957,   0.        ])], [135.71814980731443, array([ 14.57494384, 134.93326943,   0.        ])], [51.79126807717489, array([ 47.91981322, -19.64756856,   0.        ])], [37.2066034655892, array([36.87006595, -4.99295288,  0.        ])], [85.04472720162354, array([16.86495754, 83.35573665,  0.        ])], [11.979542128900121, array([-11.96663105,  -0.55603131,   0.        ])], [43.29760119387879, array([31.21680991, 30.00321729,  0.        ])], [6.7611475889447386, array([-6.74611218, -0.4506519 ,  0.        ])], [88.20665642492632, array([83.82556557, 27.45339313,  0.        ])], [32.455422825708524, array([32.34162293, -2.71549203,  0.        ])], [87.99204739221351, array([-11.90621218,  87.1828109 ,   0.        ])], [47.239633732452965, array([47.16250928, -2.69827977,  0.        ])], [48.85763670667016, array([46.00591425, 16.44762957,  0.        ])], [38.73760732381845, array([1.86209646e-02, 3.87376028e+01, 0.00000000e+00])], [39.75151494127021, array([28.72927641, 27.47383514,  0.        ])], [146.20142469168752, array([ 97.08831104, 109.31018452,   0.        ])], [87.94383972588496, array([-44.84252741,  75.65227479,   0.        ])], [57.56671926585097, array([44.44900495, 36.58159546,  0.        ])], [59.0056982639959, array([36.4562373 , 46.39628422,  0.        ])], [82.97208433159717, array([81.30995031, 16.52448966,  0.        ])], [72.95514295511724, array([-15.48920472,  71.29191694,   0.        ])], [93.16749767129505, array([ 88.67451467, -28.58344049,   0.        ])], [88.72308287513549, array([63.04390641, 62.42796888,  0.        ])], [197.6213000319093, array([-166.36225668,  106.66666667,    0.        ])], [190.7551088690294, array([-166.36225668,   93.33333333,    0.        ])], [184.5979426985148, array([-166.36225668,   80.        ,    0.        ])], [179.22289165441057, array([-166.36225668,   66.66666667,    0.        ])], [174.70216052747773, array([-166.36225668,   53.33333333,    0.        ])], [171.10347877388162, array([-166.36225668,   40.        ,    0.        ])], [168.485938759397, array([-166.36225668,   26.66666667,    0.        ])], [166.89571062882933, array([-166.36225668,   13.33333333,    0.        ])], [166.3622566825906, array([-1.66362257e+02, -9.23705556e-14,  0.00000000e+00])], [166.89571062882936, array([-166.36225668,  -13.33333333,    0.        ])], [168.48593875939702, array([-166.36225668,  -26.66666667,    0.        ])], [171.10347877388165, array([-166.36225668,  -40.        ,    0.        ])], [174.7021605274778, array([-166.36225668,  -53.33333333,    0.        ])], [179.22289165441066, array([-166.36225668,  -66.66666667,    0.        ])], [184.59794269851486, array([-166.36225668,  -80.        ,    0.        ])], [190.7551088690295, array([-166.36225668,  -93.33333333,    0.        ])], [197.6213000319094, array([-166.36225668, -106.66666667,    0.        ])], [195.36444204397887, array([183.63774332,  66.66666667,   0.        ])], [191.22569182815153, array([183.63774332,  53.33333333,   0.        ])], [187.94366382166422, array([183.63774332,  40.        ,   0.        ])], [185.5638215865955, array([183.63774332,  26.66666667,   0.        ])], [184.12115182262062, array([183.63774332,  13.33333333,   0.        ])], [183.6377433174094, array([ 1.83637743e+02, -7.10542736e-15,  0.00000000e+00])], [184.12115182262062, array([183.63774332, -13.33333333,   0.        ])], [185.5638215865955, array([183.63774332, -26.66666667,   0.        ])], [187.94366382166422, array([183.63774332, -40.        ,   0.        ])], [191.22569182815153, array([183.63774332, -53.33333333,   0.        ])], [195.36444204397887, array([183.63774332, -66.66666667,   0.        ])]]

In [16]:
?a.sort

Docstring:
a.sort(axis=-1, kind=None, order=None)

Sort an array in-place. Refer to `numpy.sort` for full documentation.

Parameters
----------
axis : int, optional
    Axis along which to sort. Default is -1, which means sort along the
    last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort under the covers and, in general, the
    actual implementation will vary with datatype. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still be used, in the order in which
    they come up in the dtype, to b

In [7]:
a = array([1, 2, 3])

In [12]:
[1, 2, 3] + [4]

[1, 2, 3, 4]

In [10]:
N

[[2.232185784639499, array([-0.80396527,  2.08237682,  0.        ])],
 [6.7611475889447386, array([-6.74611218, -0.4506519 ,  0.        ])],
 [11.979542128900121, array([-11.96663105,  -0.55603131,   0.        ])],
 [17.925815527195017, array([ 9.65582544, 15.10297644,  0.        ])],
 [19.548435604917902, array([-12.29999289, -15.19379839,   0.        ])],
 [26.523364088999582, array([-24.47867278,  10.21192546,   0.        ])],
 [32.455422825708524, array([32.34162293, -2.71549203,  0.        ])],
 [35.387904059745125, array([-34.83788875,  -6.21492248,   0.        ])],
 [35.78496555251286, array([-27.79970875,  22.53308574,   0.        ])],
 [37.2066034655892, array([36.87006595, -4.99295288,  0.        ])],
 [38.32438558696876, array([-34.00276514,  17.67966327,   0.        ])],
 [43.29760119387879, array([31.21680991, 30.00321729,  0.        ])],
 [47.239633732452965, array([47.16250928, -2.69827977,  0.        ])],
 [48.02670552674753, array([  3.60640639, -47.89110853,   0.     

In [4]:
N = [[7, np.array([0.2, 0.1, 0.3])], [2, np.array([0.3, 0.1, 0.3])], [4, np.array([0.5, 0.1, 0.3])], [5, np.array([0.2, 0.1, 0.9])]]

In [11]:
N.sort()

In [5]:
N

[[2, array([0.3, 0.1, 0.3])],
 [4, array([0.5, 0.1, 0.3])],
 [5, array([0.2, 0.1, 0.9])],
 [7, array([0.2, 0.1, 0.3])]]

In [6]:
np.mean(np.array([[1, 2, 3], [4, 5, 7]]), axis = 0)

array([2.5, 3.5, 5. ])

In [6]:
issubclass(SSND, DSSA)

True

In [11]:
getPointToSegmentProjection(np.array([0, 0]), np.array([0.5, 0]), np.array([0, 1]))

array([0.4, 0.2])

In [6]:
arr = np.array([5, 4, 3, 5, 7])
arr[np.array([1, 2, 3, 0, 2]) > 0]

array([5, 4, 3, 7])

In [8]:
np.array([1, 2, 3]).transpose()

array([1, 2, 3])

In [11]:
np.ones([4, 5]).T / np.array([1, 2, 3, 4])

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ],
       [1.        , 0.5       , 0.33333333, 0.25      ]])

In [7]:
np.roll([[1, 2], [3, 4], [5, 6]], 2)

array([[5, 6],
       [1, 2],
       [3, 4]])

In [ ]:
#Multiple running
for i, sceneGenerator in enumerate(scenes):
    A = As[i]
    algorithms = [CSA(), SA(), SODA(A), DSSA(A), SSND(A), VFASF(), SWARM()]
    for algorithm in algorithms:
        runSimulator(sceneGenerator, algorithm, metricsPrint, widths[i], heights[i], np.array([widths[i] * 0.5, heights[i] * 0.5, 0]))

In [2]:
A = 1000 * 1000 - 100 * 100 * 2
algorithms = [CSA(), SA(), SODA(A), DSSA(A), SSND(A), VFASF(), SWARM()]    

for algorithm in algorithms:
    runSimulator(TwoBoxesSceneGenerator(), algorithm, metricsPrint)

35	3.92	119.17467927804609	2.556042308902794	93.11881005853981	0.10394360474669387	2.1479790090984223
35	3.16	107.65621931585142	2.545764175052714	91.06715511210928	0.2071766331556812	2.3033596631745286
35	48.0	4679.908460291121	2.1129632474818782	80.98284304701593	0.4178815640101852	3.2443866766837672
35	48.0	6533.0215528711005	2.1680741238281382	81.15312396450793	0.4206415865149754	3.11062712230728
35	48.0	1185.8797523962905	2.0679481697827367	80.76746069732337	0.40392447352900807	3.2555133918132935
35	7.54	84.29674119330431	2.0141888813499236	81.33721144287766	0.30233906088264684	3.354970744124546
35	48.0	6713.616577632802	2.0285947952760726	74.92636500865211	0.39984984609230473	4.976616332153699


In [1]:
runSimulator(ZigZagSceneGenerator(), SA(), metricsPrint)

NameError: name 'runSimulator' is not defined

In [3]:
runSimulator(OSceneGenerator(), SWARM(), metricsPrint)

In [ ]:
import simulator_executor
from simulator_executor import runSimulator
from SWARM_algorithm import SWARMAlgorithm as SWARM
from VFASF_algorithm import VFASFAlgorithm as VFASF
import scene_preparer
from scene_preparer import *
import threading

class simulatorThread(threading.Thread):
    def __init__(self, sceneGenerator, spawnCenter, algorithm, algName, pathToResults):
        threading.Thread.__init__(self)
        self.sceneGenerator = sceneGenerator
        self.spawnCenter = spawnCenter
        self.algorithm = algorithm
        self.file = open(pathToResults, "a")
        self.algName = algName

    def metricsFileWriter(self, rCnt, elapsedTime, energy, meanDistance, covaragePercentage, uniformity, sensorCoverageUniformity):
        print(self.algName+"\t"+str(rCnt) + "\t" + str(elapsedTime) + "\t" + str(energy) + "\t" + str(meanDistance) + "\t" + str(covaragePercentage) + "\t" + str(uniformity) + "\t" + str(sensorCoverageUniformity))
        self.file.write(str(rCnt) + "\t" + str(elapsedTime) + "\t" + str(energy) + "\t" + str(meanDistance) + "\t" + str(covaragePercentage) + "\t" + str(uniformity) + "\t" + str(sensorCoverageUniformity) + "\n")
    
    def run(self):
        print('Start ' + self.algName)
        runSimulator(self.sceneGenerator, self.spawnCenter, self.algorithm, self.metricsFileWriter)
        self.file.close()
        print('End ' + self.algName)

tVFASFOScene = simulatorThread(generateOscene, np.array([-300, 0, 0]), VFASF(), 'VFASFOScene', 'VFASFOSceneResults.txt')
tVFASFZigZagScene = simulatorThread(generateZigZagScene, np.array([-500, 0, 0]), VFASF(), 'VFASFZigZagScene', 'VFASFZigZagSceneResults.txt')
tVFASFButterflyScene = simulatorThread(generateButterflyScene, np.array([-300, 0, 0]), VFASF(), 'VFASFButterflyScene', 'VFASFButterflySceneResults.txt')
tSWARMOScene = simulatorThread(generateOscene, np.array([-300, 0, 0]), SWARM(), 'SWARMOScene', 'SWARMOSceneResults.txt')
tSWARMZigZagScene = simulatorThread(generateZigZagScene, np.array([-500, 0, 0]), SWARM(), 'SWARMZigZagScene', 'SWARMZigZagSceneResults.txt')
tSWARMButterflyScene = simulatorThread(generateButterflyScene, np.array([-300, 0, 0]), SWARM(), 'SWARMButterflyScene', 'SWARMButterflySceneResults.txt')

tVFASFOScene.start()
tVFASFZigZagScene.start()
tVFASFButterflyScene.start()
tSWARMOScene.start()
tSWARMZigZagScene.start()
tSWARMButterflyScene.start()
